ontologies=core,lexinfo,oewn,ro,head-ontology,sahr-relations
ontology.core.resources=ontology/ontolex.rdf
ontology.lexinfo.resources=ontology/lexinfo.owl
ontology.oewn.resources=ontology/english-wordnet-2025.ttl.gz
ontology.ro.resources=ontology/ro.owl
ontology.head-ontology.resources=ontology/head-ontology.ttl
ontology.sahr-relations.resources=ontology/sahr-relations.ttl
heads=assertion-insertion,graph-retrieval,relation-query,dependency-chain,relation-propagation,subgoal-expansion,containment-propagation,surface-contact-propagation,ontology-reasoning,query-alignment
